# Generated by Django 3.1.14 on 2023-01-26 05:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, verbose_name="Modified"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                ("artist", models.CharField(max_length=255, verbose_name="Artist")),
                ("album", models.CharField(max_length=255, verbose_name="Album")),
                ("duration", models.DurationField(verbose_name="Duration")),
                (
                    "favorite",
                    models.BooleanField(
                        blank=True, default=False, verbose_name="Favorite"
                    ),
                ),
                (
                    "private",
                    models.BooleanField(
                        blank=True, default=True, verbose_name="Private"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Song",
                "verbose_name_plural": "Songs",
            },
        ),
    ]
